### ISSUE TITLE
NuGet package install broken for .NET 4.5 WPF project

### ISSUE THREAD

**Issue by Eagle3386** [databinding-gmbh/T4.FileManager.VisualStudio#1]
While upgrading from TemplateManager to T4.FileManager in aforementioned project, I noticed no file was added to project's root folder.
Maybe this is due to the package only targeting `netcore`, `netcoreapp` and `netstandard` (according to the `build` folder provided by the downloaded NuGet package)?

If so, please support such .NET versions too, because using VS 2019, I had no problems running it after the file's manual addition to the project.

**Comment by databinding-bot-zz** [comment]
Actually it should also be supported for the normal Full Framework. I will have a look at this.

**Comment by databinding-bot-zz** [comment]
I have tested it with wpf .NET Framework 4.5. Maybe this is a special case.
![image](https://user-images.githubusercontent.com/62669910/86284299-e65bcb80-bbe2-11ea-8f5d-05bdc43dcccb.png)

**Comment by Eagle3386** [comment]
I'll try on my end tomorrow, too.

**Comment by Eagle3386** [comment]
Sorry for being *that* late, but anyway: I hereby confirm everything works as expected, hence closing this issue. 🥳
