### ISSUE TITLE
Link to .ttinclude doesn't work in .net 5 project

### ISSUE THREAD

**Issue by boone34** [databinding-gmbh/T4.FileManager.VisualStudio#10]
After installing the nuget package the file __T4.FileManager.VisualStudio.ttinclude_ is added to the project as a **link** pointing to the file which stored under the _packages_ folder.

Including the file into a .tt using:

<#@ include file="$(ProjectDir)\T4.FileManager.VisualStudio.ttinclude" #>

Does not work in a .net 5 project using VS 2019. The error(s) are:

Failed to resolve include text for file: C:\Users\boone\Documents\TechNoir\Projects\Edmx\Explore\T4\\T4.FileManager.VisualStudio.ttinclude

and

There was an error loading the include file '$(ProjectDir)\T4.FileManager.VisualStudio.ttinclude'.

Coping _T4.FileManager.VisualStudio.ttinclude_ from packages folder to the project folder and using

<#@ include file="T4.FileManager.VisualStudio.ttinclude" #>

Works.

**Comment by renegadexx** [comment]
Hello @boone34 

NET 5 uses the nuget [package reference type](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference)

That's the reason why the $(ProjectDir)-Makro does not work in NET 5. If you use $(TargetDir) then the t4.filemanager will working. NET 5 Samples can be found in the [LivingDoc](https://databinding-gmbh.github.io/T4.FileManager.VisualStudio/T4.FileManager.NetCore.AcceptanceCriteria.dll.html#/document/Standalone/feature/e6471f9ec42e219647fd07fd1be234c9/scenario/6517082fa20221f9ef45364c9660753d) section.

Syntax:
<#@ include file="$(TargetDir)\T4.FileManager.VisualStudio.ttinclude" #>

**Comment by renegadexx** [comment]
[Documentation revised](https://databinding-gmbh.github.io/T4.FileManager.VisualStudio/02-Quick-start/)
