### ISSUE TITLE
Doc: host specific="false|true"

### ISSUE THREAD

**Issue by PhilPJL** [databinding-gmbh/T4.FileManager.VisualStudio#12]
Simple issue with documentation.  Experimenting with the V3 package in VS2022, .NET5/6 and following the quick-start (without reading every letter), and after adding `<#@ include file="$(TargetDir)\T4.FileManager.VisualStudio.ttinclude" #>` to a test .tt file resulted in:

![image](https://user-images.githubusercontent.com/271656/160871204-ecd828ba-f0c7-4eb6-acbe-162c8b122180.png)

This is because when adding a test .tt file the first line is
`<#@ template debug="false" hostspecific="**false**" language="C#" #>`

Changing this to 
`<#@ template debug="false" hostspecific="**true**" language="C#" #>`
fixes the problem.

Maybe you could highlight this?

**Comment by jgraber** [comment]
Hi PhilPJL,
We highlighted the line in the quick start example to make it clear that you must set the attribute hostspecific to true:
https://databinding-gmbh.github.io/T4.FileManager.VisualStudio/02-Quick-start/#extend-your-t4-template

Regards,
Johnny & René
