### ISSUE TITLE
BUG: .NET Framework quick-start error

### ISSUE THREAD

**Issue by PhilPJL** [databinding-gmbh/T4.FileManager.VisualStudio#13]
**Bug description**
Following quick start on .NET framework results in build failure.

**Your environment**
Version 3 of T4.FileManager:
Version 4.8 of .Net: 
Version 2022 of Visual Studio:
Operating System:  Windows 10

**Minimalistic template**
Follow the quick start which says for .NET framework add
`<#@ include file="$(ProjectDir)\T4.FileManager.VisualStudio.ttinclude" #>`

**Expected behaviour**
Should build

**What went wrong?**
Doesn't build because the .ttinclude files are generated in the 'OutDir' folder
![image](https://user-images.githubusercontent.com/271656/160877213-4420c307-d5b9-4b02-b1b0-1ff9eea342ea.png)

**Bugfix or workaround**
Workaround is to use 
`<#@ include file="$(OutDir)\T4.FileManager.VisualStudio.ttinclude" #>`

Is this a bug in the doc's or in the package?

**Comment by jgraber** [comment]
Hi PhilPJL,
If you need to use $(TargetDir) or $(ProjectDir) depends on how you integrate NuGet. If you use the new PackageReference approach, you must use $(TargetDir). If you still use the packages.config file, you must use $(ProjectDir).

We extended the documentation to make this point more clear:
https://databinding-gmbh.github.io/T4.FileManager.VisualStudio/02-Quick-start/#include-in-your-text-template

We hope this helps.

Thanks,
Johnny & René
