### ISSUE TITLE
BUG: dependency on Newtonsoft.Json

### ISSUE THREAD

**Issue by PhilPJL** [databinding-gmbh/T4.FileManager.VisualStudio#14]
The package claims to have no dependencies, but does use Newtonsoft.Json. 
This works fine in Visual Studio, I guess because VS is implicitly loading Newtonsoft.Json.  No such luck when using Jetbrains' Rider where I get 'unresolved assembly' errors when analysing the code or running the template.

**Comment by jgraber** [comment]
Hi PhilPJL,
That is the reason why the package is named T4.FileManager.**VisualStudio**. We plan to create a specific package for Rider, then there are a few other points that we need to address besides the Newtonsoft.Json (like env.dte is not fully supported in Rider).

Regards,
Johnny & René

**Comment by PhilPJL** [comment]
Ha, thanks and sorry for being a pain.  Just taken over some existing code which uses T4Immutable package, which includes V2.1 of your code.  Would ideally like to move from VS2019 to VS2022 but T4Immutable isn't maintained.  It's a learning process :)

**Comment by jgraber** [comment]
No problem. We are happy that someone shows us where the pain points are so that we can fix them.
