### ISSUE TITLE
BUG: FindProjectByName() throws an exception if Project.ProjectItems is null for any project in the solution

### ISSUE THREAD

**Issue by expyram** [databinding-gmbh/T4.FileManager.VisualStudio#17]
**Bug description**
The use of `list[i].ProjectItems.Cast<ProjectItem>()` in the function `FindProjectByName(string projectName)` assumes that ProjectItems is never null.  Some projects (e.g. Setup projects) can have a null value for ProjectItems.

**Your environment**
Version of T4.FileManager: 3.1.1
Version of .Net: 4.8 and 6.0
Version of Visual Studio: 2022
Operating System: Windows 10.0.19043.1826

**Minimalistic template**
Add the _Visual Studio Installer Projects_ extension to Visual Studio.
Create a blank solution
Add a T4 project with a template that relies on T4.FileManager.VisualStudio, e.g. with the line
`<#@ include file="$(UserProfile)\.nuget\packages\t4.filemanager.visualstudio\3.1.1\content\T4.FileManager.VisualStudio19.ttinclude" #>`
Add a Setup Project to the same solution.
Transform the T4.

**Expected behaviour**
The T4 should transform normally.

**What went wrong?**
Visual Studio records the following error:

> Running transformation: System.ArgumentNullException: Value cannot be null.
> in ...\.nuget\packages\t4.filemanager.visualstudio\3.1.1\content\T4.FileManager.VisualStudio.ttinclude:line 676

**Bugfix or workaround**
Insert this into T4.FileManager.VisualStudio.ttinclude at line 676:
`if (list[i].ProjectItems != null)`

**Comment by renegadexx** [comment]
Hello @expyram thanks for supporting this issue with bugfix. We will solve this issue asap.

**Comment by renegadexx** [comment]
With version 3.1.2 available on nuget
