### ISSUE TITLE
Cannot debug with VS2022

### ISSUE THREAD

**Issue by takthetank** [databinding-gmbh/T4.FileManager.VisualStudio#18]
**Bug description**
I can't debug with VS2022. Whenever I right click on a tt file -> Debug T4 template, 
I get an error _Unable to start transformation run creation process._.
Running the template though works fine!

**Your environment**
Version of T4.FileManager: 3.1.2
Version of .Net: .Net Standard 2.0
Version of Visual Studio: VS2022 v17.3.5
Operating System: Windows 10

**Minimalistic template**
Any simple tt file will do.

**Expected behaviour**
To start debugging the template.

**What went wrong?**
Got error "Unable to start transformation run creation process."

**Bugfix or workaround**
Workaround: launch debugger in a separate instance, found in this post [Cannot debug T4 template in VS2017](https://stackoverflow.com/questions/43184337/cannot-debug-t4-template-in-vs2017/43186284#43186284)

**Comment by jgraber** [comment]
Hi takthetank,
Does this problem also show up when you have a T4 template that does not contain our T4.FileManager?

Regards,
Johnny

**Comment by takthetank** [comment]
Hi, I tried with a plain tt and it seems it doesn't work either! 
Probably something broke in VS2022...

**Comment by jgraber** [comment]
Hi takthetank,
I agree, there is something broken in Visual Studio 2022. We tried to debug scripts with and without the T4.FileManager and as soon as we do it in Visual Studio 22, it gives us the error message you reported.  

Regards,
Johnny
