### ISSUE TITLE
BUG: Name conflict when importing System.Xml

### ISSUE THREAD

**Issue by lukasf** [databinding-gmbh/T4.FileManager.VisualStudio#20]
**Bug description**
For my project, I need to include the System.Xml namepsace in the T4 Template. But if I do that, I get a compile error.

**Your environment**
Version of T4.FileManager: Latest
Version of .Net: .NET Standard 2.1
Version of Visual Studio: 2022
Operating System: Windows 10

**Minimalistic template**

<#@ template hostspecific="true" language="C#" #>
<#@ assembly name="System.Core" #>
<#@ assembly name="System.Xml" #>
<#@ assembly name="System.Xml.Linq" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Text" #>
<#@ import namespace="System.Xml" #>
<#@ import namespace="System.Xml.Linq" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ output extension=".cs" #>
<#@ include file="$(TargetDir)\T4.FileManager.VisualStudio.ttinclude" #>
<# var manager = T4FileManager.Create(this).EnableAutoIndent(); #>

**Expected behaviour**
File is generated

**What went wrong?**
Compiling transformation: 'Formatting' is an ambiguous reference between 'Newtonsoft.Json.Formatting' and 'System.Xml.Formatting'	 T4.FileManager.VisualStudio.ttinclude 389	

**Bugfix or workaround**
If I change Formatting.Indented to Newtonsoft.Json.Formatting.Indented on line 389, everything works fine.
I recommend you change this in the official version, because System.Xml is still pretty frequently used.

Thank you for providing this tool.

**Comment by renegadexx** [comment]
Hi @lukasf 

Thank you for the suggested solution. The acceptance criteria have been added [UT001 Scenario: Generate file with System.Xml Namespace (Bug 20)] and the solution is available on NuGet with Release 3.1.3.

Regards
Rene

**Comment by lukasf** [comment]
Hi @renegadexx, cool, thank you for the fast solution!
Closing this as resolved.
