### ISSUE TITLE
BUG: Wrong file property value set

### ISSUE THREAD

**Issue by nobyArdor** [databinding-gmbh/T4.FileManager.VisualStudio#22]
**Bug description**
There is a bug in the function SetPropertyValue where it can be called with a different ProjectItem than the one linked to the generated file when there is another file in the solution with the same name. 

**Expected behaviour**
Function SetPropertyValue set value only for generated files.

**Reason**
Method T4FileManager.FindProjectItem(string projectName, string filename) in result ignore projectName parameter. 

**Suggestion**
Change the AddMissingFileToProject function result to ProjectItem and modify the T4FileManager.FindProjectItem method to have the same parameters as T4FileManager.HasProjectItem. 
Change the return type of the AddMissingFileToProject function to ProjectItem and modify the parameters of the T4FileManager.FindProjectItem function to match those of the T4FileManager.HasProjectItem function. 

**Fix example**
https://github.com/databinding-gmbh/T4.FileManager.VisualStudio/commit/0a4d9a0fdbb85d1c229253f86ffea7abf7743a0c

**Comment by renegadexx** [comment]
Sorry for the late reply.

If I have understood correctly, then you have a project “Project1” with two identically named project files “Class1”, one generated, the other not. Only the generated one should take over the setting?

I would like to record and integrate this in a Spec by Example scenario. 

Is this correct, if not, please describe an example.

Thank you very much

Rene

**Comment by nobyArdor** [comment]
Thank you for replay!

You understand the issue closely, but not fully. 
I have provided an example on GitHub: [T4Issue22Example](https://github.com/nobyArdor/T4Issue22Example).

When I run the 'ProducerProject\GenerateEmbeddedResource.tt' file, it generates the 'ConsumerProject\Data\data.json' file as expected. However, the 'BuildAction' property is set to 'EmbeddedResource' for the 'ProducerProject\Data\data.json' file."

**Comment by renegadexx** [comment]
Hello @nobyArdor
 
Thanks for clarifying the requirement and the example provided. We have included your example in the Executable Specification and made a change that is limited to the FindProjectItem method.
 
We will provide this update on NuGet with version 4.0.2.
 
Thank you for your help
 
Johnny and Rene

**Comment by nobyArdor** [comment]
Thanks a lot
