### ISSUE TITLE
Error compiling transformation, "you must add reference to assembly 'System.Runtime, Version 6.0.0.0'"

### ISSUE THREAD

**Issue by timothypbrennan** [databinding-gmbh/T4.FileManager.VisualStudio#24]
I have used the previous version of T4 Template File Manager with an earlier version of Visual Studio. I am trying to create a template using this version with Visual Studio version 17.11.2. I have created a simple test project with a basic template with no actual code. When I add the include to the "$(TargetDir)\T4.FileManager.VisualStudio.ttinclude" file. I get the following error:

Compiling transformation: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

Is there a simple fix for this or something I need to do? I've tried with a .NET Framework 4.8 project and a .NET 6.0 project and get the same error.

**Comment by renegadexx** [comment]
As of Visual Studio 17.11+, there are apparently adjustments with Newtonsoft.Json, which cause these errors with the dependencies. The dependency to Newtonsoft.Json in the core of the T4.FileManager.VisualStudio has been removed with version 4.0.1

**Comment by timothypbrennan** [comment]
Thanks for the update!
