### ISSUE TITLE
(Re-) Enable addition of typical "auto-generated" header to generated files

### ISSUE THREAD

**Issue by Eagle3386** [databinding-gmbh/T4.FileManager.VisualStudio#3]
There's a default code added to generated files by VS:
```csharp
//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by {Path.GetFileName(Host.TemplateFile)}.
//
//     Changes to this file may cause incorrect behavior and will be lost if the
//     code is regenerated.
//     For persistent customizations of this class, create another equally named
//     partial class and implement them there.
// </auto-generated>
//------------------------------------------------------------------------------
```
With T4.FileManager, this header is not added to generated files - IIRC, the old TemplateManager didn't generate it, too.

Sure, there's `manager.StartHeader()` and `manager.FinishHeader()` to achieve a similar goal. But IMHO those methods are for adding custom headers, not the aforementioned default one.

Hence, this issue aims for enabling its pass-through, at least via an (maybe optional) property, e. g. `IsDefaultAutoGeneratedHeaderEnabled`.

**Comment by databinding-bot-zz** [comment]
I think that's a good idea. We will put it on our road map.

**Comment by Eagle3386** [comment]
Thanks a lot, Thierry! Looking forward to it! As a minor edit, I've corrected the `auto-generated` header as it, IMHO at least, should reflect such information like the actual T4 template which created the file.

**Comment by jgraber** [comment]
We currently think that the custom header is the better place to implement such a header. The T4.FileManager should be able to create various types of files and not everywhere is it possible to use this format for a header (JSON or SQL as an example). Therefore, we will not implement this feature.
