### ISSUE TITLE
Manager does not remove folder from project

### ISSUE THREAD

**Issue by Rickrat** [databinding-gmbh/T4.FileManager.VisualStudio#4]
This is really a fantastic tool!

`mgr.CreateNewFile(model1.Name + ".txt", "T4Test", @"GeneratedCode\ModelsA", null);`

then change to

`mgr.CreateNewFile(model1.Name + ".txt", "T4Test", @"GeneratedCode\ModelsB", null);`

You will see the file did in fact move, but the previous folder, **ModelsA**, did not get removed from the project.

**Comment by Rickrat** [comment]
I would like to request that it makes a list of files/folders that were generated and remove them upon generation, instead of the json.
Example (from above comment)

$(ProjectDir)\Generatedode\ModelsA\
$(ProjectDir)\Generatedode\ModelsA\model.txt
$(ProjectDir)\Generatedode\ModelsB\
$(ProjectDir)\Generatedode\ModelsB\model.txt

**Comment by databinding-bot-zz** [comment]
Thanks for your feedback! 

This is a known improvement. Feel free to make a pull request. :smiley:

**Comment by Rickrat** [comment]
Thank you @db-ty . I've thought about it. I am unable to contribute a working example of it removing the folder, it's like VS has a lock on the folder.
