### ISSUE TITLE
 unchanged files aren't skipped

### ISSUE THREAD

**Issue by HADDADENICAR** [databinding-gmbh/T4.FileManager.VisualStudio#8]
After running custom tools , all the files even the ones that i didn't change are regenerated ,which isn't expected and wasn't in previous versions

**Comment by renegadexx** [comment]
Hi @HADDADENICAR 

- Which version was the previous one with the expected behaviour, which is your current one?
- Which .net version do you use?
- Which Visual Studio Version do you use?

Please provide a sample t4 script, so that we can reproduce the error.

Regards
@renegadexx and @jgraber

**Comment by jgraber** [comment]
Hi @HADDADENICAR 
Is this still an issue for you? If so, please provide some details to help us reproduce this error.

Regards,
Johnny
