### ISSUE TITLE
Visual Studio 2022 Breaking Change

### ISSUE THREAD

**Issue by BenKmann** [databinding-gmbh/T4.FileManager.VisualStudio#9]
I get some Errors in Visual Studio 2022, that i didn't have in VS 2019:

Compiling transformation: The type 'DTE' exists in both 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'Microsoft.VisualStudio.Interop, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	Miscellaneous Files	T4.FileManager.ttinclude     748

And also with some other Types like ProjectItem:
Compiling transformation: The type 'ProjectItem' exists in both 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'Microsoft.VisualStudio.Interop, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	Miscellaneous Files	T4.FileManager.ttinclude	537	

Apparently VS 2022 has some Breaking Changes regarding DTE:
https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/breaking-api-list?view=vs-2022#dte-and-_dte-type-cast-failures

**Comment by BenKmann** [comment]
Apparently Visual Studio already Imports the DLLs.
If I Remove 
`﻿<#@ assembly name="EnvDTE" #>`
in Line 1 https://github.com/databinding-gmbh/T4.FileManager.VisualStudio/blob/master/src/T4.FileManager.VisualStudio.ttinclude#L1 
I can generate Files with VS 2022 but not with VS 2019, because VS 2019 needs this Import and VS 2022 doesn't need it.

**Comment by jgraber** [comment]
Hi Ben,
Thanks for figuring out the necessary changes to run our T4 FileManager in Visual Studio 2022. It sounds as if we need a separate package for VS 2022. I will check with René to publish something in time of the official release event for VS 2022 and .Net 6.

Regards,
Johnny

**Comment by renegadexx** [comment]
[New version available](https://www.nuget.org/packages/T4.FileManager.VisualStudio/3.0.0)
